[build]
  command = "npm run build"
  publish = "dist/client"

[dev]
  command = "npm run dev"

# Desactivar el caché para todo el contenido
[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "no-store, no-cache, must-revalidate, proxy-revalidate"